// UI components
export { default as GradientText } from './GradientText'
export { default as VariableProximity } from './VariableProximity'
export { default as VariableProximityManager } from './VariableProximityManager'
export { default as ScrollProgress } from './ScrollProgress'
export { default as SocialLinks } from './SocialLinks'
export { default as WorkCard } from './WorkCard'
export { default as WorkGrid } from './WorkGrid'
export { default as PerformanceList } from './PerformanceList'
export { default as ProjectList } from './ProjectList'
export { default as ThreeColumnLayout } from './ThreeColumnLayout'
export { default as InteractiveCursor } from './InteractiveCursor'
export { default as InteractiveService } from './InteractiveService'
export { default as Services } from './Services'
export { default as Skills } from './Skills'
export { default as EasterEggManager } from './EasterEggManager'
